"""Analysis tasks

Revision ID: 09f7faf843f2
Revises: 73d3d2bc28a2
Create Date: 2021-09-07 00:27:51.603017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f7faf843f2'
down_revision = '73d3d2bc28a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('analysis_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('dataset_filename', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'dataset_filename')
    op.drop_column('task', 'analysis_id')
    op.drop_table('analysis_task')
    # ### end Alembic commands ###
